# Copyright 2020 Canonical Ltd.
# Licensed under the AGPLv3, see LICENCE file for details.

ARG BASE_IMAGE
FROM $BASE_IMAGE

# Add the juju and sjuju user for rootless agents.
# 170 and 171 uid/gid is sourced from juju/juju
RUN groupadd --gid 170 juju
RUN useradd --uid 170 --gid 170 --no-create-home --shell /usr/bin/bash juju
RUN groupadd --gid 171 sjuju
RUN useradd --uid 171 --gid 171 --no-create-home --shell /usr/bin/bash sjuju
RUN mkdir -p /etc/sudoers.d && echo "sjuju ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/sjuju

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo \
    python3-yaml \
    python3-pip \
    python3-setuptools \
    # for debug-hooks.
    tmux byobu \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.cache

ENTRYPOINT ["sh", "-c"]

